# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 10:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20181103_1307'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postpluginmodel',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
    ]
