# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 10:14
from __future__ import unicode_literals

import cms.models.fields
from django.db import migrations, models
import django.db.models.deletion
import djangocms_text_ckeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('posts', '0003_auto_20181103_1308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='link',
        ),
        migrations.RemoveField(
            model_name='postpluginmodel',
            name='post',
        ),
        migrations.AddField(
            model_name='postpluginmodel',
            name='description',
            field=djangocms_text_ckeditor.fields.HTMLField(blank=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='postpluginmodel',
            name='link',
            field=cms.models.fields.PageField(default=None, on_delete=django.db.models.deletion.CASCADE, to='cms.Page', verbose_name='Ссылка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postpluginmodel',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Заголовок'),
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
