# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20181103_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpluginmodel',
            name='description',
        ),
        migrations.AddField(
            model_name='postpluginmodel',
            name='body',
            field=models.TextField(default=None, verbose_name='body'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postpluginmodel',
            name='cmsplugin_ptr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='posts_postpluginmodel', serialize=False, to='cms.CMSPlugin'),
        ),
    ]
