# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-11-03 13:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_remove_postpluginmodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpluginmodel',
            name='title',
            field=models.CharField(default='', max_length=255, verbose_name='Заголовок'),
        ),
    ]
