# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-17 19:21
from __future__ import unicode_literals

import colorfield.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('djangocms_link', '0013_fix_hostname'),
        ('djangocms_file', '0010_removed_null_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileWithBackgroundColor',
            fields=[
                ('file_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangocms_file.File')),
                ('file_background_color', colorfield.fields.ColorField(default='#f8f8f8', max_length=18, verbose_name='Цвет фона')),
            ],
            options={
                'abstract': False,
            },
            bases=('djangocms_file.file',),
        ),
        migrations.CreateModel(
            name='LinkWithBackgroundColor',
            fields=[
                ('link_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='djangocms_link.Link')),
                ('background_color', colorfield.fields.ColorField(default='#f8f8f8', max_length=18, verbose_name='Цвет фона')),
            ],
            options={
                'abstract': False,
            },
            bases=('djangocms_link.link',),
        ),
    ]
