# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-29 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0020_old_tree_cleanup'),
        ('custom_plugins', '0003_auto_20181029_2018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filelinkwithbackgroundcolor',
            name='file_ptr',
        ),
        migrations.RemoveField(
            model_name='linkwithbackgroundcolor',
            name='link_ptr',
        ),
        migrations.DeleteModel(
            name='FileLinkWithBackgroundColor',
        ),
        migrations.DeleteModel(
            name='LinkWithBackgroundColor',
        ),
    ]
